### PR TITLE
Multiple Language Support

### PR DESCRIPTION
**Pull request by XKaguya**
This feature is based on the `gettext` module. It will load localization before the window appears. I have no clue about how to do this in real-time.

Localization repository: [https://github.com/XKaguya/OSCR-Localization](https://github.com/XKaguya/OSCR-Localization)

No issues have been found so far.

The currently localization was machine translate. Which might not be right.

image
image

I can't modify the messages that using the `OSCR` package currently because its hard code.

### CODE REVIEW

**Comment by Kraust** [comment]
Changes look good. Just let us know whenever you're done.

**Comment by XKaguya** [comment]
It is done, I think. I tested it myself and did not find anything that may be broken by me. It may still need further testing.

Currently, the language is loaded before the `leagueapi`. The language file is located in the `locales` folder. However, changing the language option requires modifying the source code. 

So far, we have support for four languages. All translations were done using Google Translate, which may not be entirely accurate. 

If you notice any issues or have suggestions, please feel free to [open an issue](https://github.com/XKaguya/OSCR-Localization/issues) or [make a pull request](https://github.com/XKaguya/OSCR-Localization/pulls) in this repository.

The localization process is straightforward. Fork my [localization repo](https://github.com/XKaguya/OSCR-Localization) and follow these steps (this might change in the future):

1. Copy the `messages.po` file inside `locales\en\LC_MESSAGES`.
2. Create a folder with the correct name and put the modified `messages.po` inside it. It should look like this: `locales\YOUR_LANGUAGE\LC_MESSAGES\messages.po`.
3. Make a pull request to me, and I'll handle the formatting. This step also requires changing the OSCR's source code.

I have no plans to translate `Player` and `NPC` because I think there's no need to translate these two words.

There are also words that cannot be translated, such as the server's response. Doing so would make the code messy, as I don't want to include a lot of dictionaries in the code.

**Comment by Kraust** [comment]
Only comment right now is that we'll probably want to move over the repo to the STOCD account at some point.

**Comment by XKaguya** [comment]
And yes that is what i think too. But i dont know how exactly i don't know github well



---Original---
From: ***@***.***&gt;
Date: Sat, Aug 3, 2024 22:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [STOCD/OSCR-UI] Multiple Language Support (PR #43)




 
Only comment right now is that we'll probably want to move over the repo to the STOCD account at some point.

**Comment by Kraust** [comment]
We can either fork the repo or the ownership can be transferred. Not a huge issue. Will merge and test unless @Shinga13 has any objections.

**Pull request merged**
